---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-api
  labels:
    app: pokemon-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-api
  # pod spec begins here
  template:
    metadata:
      labels:
        app: pokemon-api
    spec:
      containers:
        - name: pokemon-api
          image: registry.digitalocean.com/abdfahmia/docker-flask:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
          - name: FLASK_APP
            value: "app.py"
              
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pokemon-secret
                key: db_root_password

          - name: DB_NAME
            value: pokemon_data

          - name: DB_USER
            value: root

          - name: DB_HOST
            value: 10.245.121.217

          command: ["flask", "run", "--host", "0.0.0.0"]