---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-api
  labels:
    app: pokemon-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-api
  # pod spec begins here
  template:
    metadata:
      labels:
        app: pokemon-api
    spec:
      containers:
        - name: pokemon-api
          image: registry.digitalocean.com/abdfahmia/docker-flask:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
          - name: FLASK_APP
            value: "app.py"
              
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pokemon-secret-password
                key: db_root_password

          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: pokemon-secret-name
                key: db_name

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: pokemon-secret-user
                key: db_user

          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: pokemon-secret-host
                key: db_host

          command: ["flask", "run", "--host", "0.0.0.0"]