---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-api
  labels:
    app: pokemon-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-api
  # pod spec begins here
  template:
    metadata:
      labels:
        app: pokemon-api
    spec:
      containers:
        - name: pokemon-api
          image: abdfahmia/flask-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
          - name: FLASK_APP
            value: "app.py"
          command: ["flask", "run", "--host", "0.0.0.0"]  